import { resolveLabel } from "./labels";

/**
 * A text snapshot of every form control on the page.
 *
 * Adapters for Greenhouse and Workday could be written against public docs and
 * stable `data-automation-id` hooks. TikTok has neither: its markup is
 * generated by Arco Design with hashed class names and no automation
 * attributes, so the only way to know what a selector should be is to look at
 * the real page. This produces something the user can copy out of the popup and
 * paste back, instead of us guessing at label text and picker internals.
 *
 * Values are deliberately *not* included — the whole point of this extension is
 * that personal data stays local, and a dump the user pastes into a chat would
 * leak it.
 */

const CONTROL_SELECTOR = [
  "input",
  "textarea",
  "select",
  '[role="combobox"]',
  '[role="listbox"]',
  "button",
].join(", ");

const SECTION_TITLE_SELECTOR = "h1, h2, h3, h4, h5, legend, [role='heading']";

/**
 * Attributes worth knowing about when writing a selector.
 *
 * `readonly` and `disabled` are here because they decide whether a control is
 * considered fillable at all. Leaving them out cost a whole debugging round:
 * TikTok's work-authorization comboboxes are readonly pickers, the dump gave no
 * hint of it, and they silently reported "select not found".
 */
const INTERESTING_ATTRS = [
  "id",
  "name",
  "type",
  "placeholder",
  "role",
  "readonly",
  "disabled",
  "aria-label",
  "aria-haspopup",
  "aria-expanded",
];

function collapse(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`;
}

function dataAttrs(el: Element): string[] {
  return Array.from(el.attributes)
    .filter((a) => a.name.startsWith("data-"))
    .slice(0, 4)
    .map((a) => `${a.name}="${truncate(a.value, 40)}"`);
}

/**
 * Which section a control belongs to.
 *
 * Heading elements were the first thing tried and they were useless here: this
 * site uses none, so the search climbed past the form entirely and grouped
 * fields under the page footer ("Legal", "Company"). The reliable signal is the
 * form's own id scheme — `education[1].school` says "education" outright.
 *
 * The heading walk stays as a fallback for sites that do use headings, but it is
 * bounded to 6 levels and skips siblings containing form controls, so it can't
 * wander into a neighbouring field or off the form.
 */
function sectionOf(el: Element): string {
  const id = el.getAttribute("id") ?? innerId(el);
  const indexed = id?.match(/^([A-Za-z_$][\w$]*)\s*\[/);
  if (indexed) return `${indexed[1]}[] (indexed section)`;

  let node: Element | null = el;
  for (let depth = 0; depth < 6 && node; depth++) {
    let sibling: Element | null = node.previousElementSibling;
    while (sibling) {
      const heading = sibling.matches(SECTION_TITLE_SELECTOR)
        ? sibling
        : sibling.querySelector(SECTION_TITLE_SELECTOR);
      const text = collapse(heading?.textContent ?? "");
      if (text && text.length <= 80) return text;
      sibling = sibling.previousElementSibling;
    }
    node = node.parentElement;
  }
  return "(no section heading)";
}

/**
 * A combobox wrapper carries no id — the id sits on the search input inside it.
 * Reporting it on the wrapper too is what makes the `education[1].degree`
 * relationship visible.
 */
function innerId(el: Element): string | null {
  return el.querySelector("input[id], textarea[id], select[id]")?.id ?? null;
}

/**
 * Text belonging directly to this element, ignoring descendants.
 *
 * Section titles and question prompts on this site are plain divs, so they never
 * show up as headings or labels. Listing them separately is the only way to see
 * what a `containerHeadingPatterns` regex actually has to match.
 */
function ownText(el: Element): string {
  return collapse(
    Array.from(el.childNodes)
      .filter((n) => n.nodeType === Node.TEXT_NODE)
      .map((n) => n.textContent ?? "")
      .join(" "),
  );
}

function textLandmarks(): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const el of Array.from(document.querySelectorAll("body *"))) {
    const text = ownText(el);
    if (text.length < 2 || text.length > 90) continue;
    if (seen.has(text)) continue;
    seen.add(text);
    out.push(`${el.tagName.toLowerCase()}: "${text}"`);
    if (out.length >= 150) break;
  }
  return out;
}

function describe(el: Element): string {
  const parts: string[] = [el.tagName.toLowerCase()];
  for (const name of INTERESTING_ATTRS) {
    if (!el.hasAttribute(name)) continue;
    const value = collapse(el.getAttribute(name) ?? "");
    /* Bare boolean attributes read back as "" — report presence, not the value. */
    parts.push(value ? `${name}="${truncate(value, 40)}"` : name);
  }
  parts.push(...dataAttrs(el));

  const classes = collapse(el.getAttribute("class") ?? "")
    .split(" ")
    .filter((c) => c && !/^[a-z]*-?[0-9a-f]{5,}$/i.test(c))
    .slice(0, 4);
  if (classes.length) parts.push(`class="${classes.join(" ")}"`);

  const inner = el.getAttribute("id") ? null : innerId(el);
  if (inner) parts.push(`inner-id="${inner}"`);

  const head = `<${parts.join(" ")}>`;
  if (el.tagName === "BUTTON") {
    const text = truncate(collapse(el.textContent ?? ""), 40);
    return text ? `${head} text: "${text}"` : head;
  }
  const label = resolveLabel(el);
  return label ? `${head} label: "${truncate(label, 80)}"` : `${head} (no label)`;
}

export function dumpForm(): string {
  const bySection = new Map<string, string[]>();
  for (const el of Array.from(document.querySelectorAll(CONTROL_SELECTOR))) {
    if (el.getAttribute("aria-hidden") === "true") continue;
    if (el instanceof HTMLInputElement && el.type === "hidden") continue;
    const section = sectionOf(el);
    const list = bySection.get(section) ?? [];
    list.push(describe(el));
    bySection.set(section, list);
  }

  const lines = [`# ${window.location.hostname} — form structure`, ""];
  for (const [section, controls] of bySection) {
    lines.push(`## ${section}`);
    for (const c of controls) lines.push(`  ${c}`);
    lines.push("");
  }
  lines.push(`(${document.querySelectorAll(CONTROL_SELECTOR).length} controls)`);

  /*
   * Section titles and question prompts are plain divs here, so they appear in
   * none of the control lines above. Without this block there's no way to tell
   * what text a section-title regex has to match.
   */
  lines.push("", "## text landmarks (section titles, prompts, labels)");
  for (const t of textLandmarks()) lines.push(`  ${t}`);
  return lines.join("\n");
}
